enum AuthorizationEnum {
  DASHBOARD = "DASHBOARD",
  SEVAKENDRA_SETUP = "SEVAKENDRA_SETUP",
  SEVAKENDRA_USERS = "SEVAKENDRA_USERS",
  TYPE_MASTERS = "TYPE_MASTERS",
  DIVYANG_DETAILS = "DIVYANG_DETAILS",
  SERVICE_MASTER = "SERVICE_MASTER",
  SERVICE_MAPPING = "SERVICE_MAPPING",
  POST_SERVICE_MAPPING = "POST_SERVICE_MAPPING",
  GET_SERVICE_MAPPING = "GET_SERVICE_MAPPING",
}

enum DivyangAuthorizationEnum {
  DIVYANG_DETAILS = "DIVYANG_DETAILS",
  POST_SERVICE_MAPPING = "POST_SERVICE_MAPPING",
  GET_SERVICE_MAPPING = "GET_SERVICE_MAPPING",
}

export { AuthorizationEnum, DivyangAuthorizationEnum };
