enum AuthorizationEnum {
  DASHBOARD = "DASHBOARD",
  SEVAKENDRA_SETUP = "SEVAKENDRA_SETUP",
  SEVAKENDRA_USERS = "SEVAKENDRA_USERS",
  TYPE_MASTERS = "TYPE_MASTERS",
  DIVYANG_DETAILS = "DIVYANG_DETAILS",
  SERVICE_MASTER = "SERVICE_MASTER",
  SERVICE_MAPPING = "SERVICE_MAPPING",
}

enum MethodsEnum {
  DEFAULT = "",
  GET = "GET",
  GET_BY_ID = "GET_BY_ID",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
}

export { AuthorizationEnum, MethodsEnum };
