name: Production
run-name: ${{ github.actor }} pushed to prod - ${{ github.ref_name }}
on: 
  push:
    branches:
      - main

env:
  NODE_ENV: production
  DATABASE_URL: postgresql://48d8147f-7405-4b46-8f30-118298f2aa24-user:pw-6172e172-2faf-4b89-8ded-399f04881da3@postgres-free-tier-v2020.gigalixir.com:5432/48d8147f-7405-4b46-8f30-118298f2aa24?connection_limit=1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get PNPM Store Directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup PNPM Cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install

      - name: Prisma Generate
        run: pnpm prisma generate

      - name: Build Backend
        working-directory: ./backend
        run: pnpm tsc --build